import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from 'components/Navbar'
import MainBody from 'components/MainBody'
import {Box} from "@mui/system";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Feature Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <Navbar></Navbar>
        <Box mr={8} ml={8}>
            <MainBody></MainBody>
        </Box>



    </>
  )
}
